
export const DUPLICATE_ACCOUNT_ERROR: string = "An account with this email exists. Login or choose another email address"
export const DUPLICATE_BANK_ERROR: string = "A bank account with this credetials exists"
export const INVALID_LOGIN_ERROR: string = "You have entered an invalid username or password"
export const DUPLICATE_ADD_ON_REQUEST_ERROR: string = "A pending request was found. Kindly wait or contact customer service"
export const INVALID_OTP: string = "You have entered an invalid (O)ne (T)ime (P)assword"
export const INVALID_ACCESS_TIME: string = "You must set time within 24 hours"
export const PAST_ACCESS_TIME: string = "You can not set time in the past"
export const DUPLICATE_COMMUNITY_JOIN_REQUEST: string = "You have a pending request. Kindly wait until its approved or contact the community admin"
export const DUPLICATE_COMMUNITY_MEMBER_REQUEST: string = "You are already a member of this residential/social community"
export const INVALID_INVITE_VALIDITY: string = "You must enter a time in the future"
export const INVALID_INVITE_VALIDITY_PERIOD_HOUR: string = "You must enter a validity period between 1 to 9 hours"
export const INVALID_INVITE_VALIDITY_PERIOD_DAY: string = "You must enter a validity period not more than 7 days"
export const INVALID_COMMUNITY_PATH: string = "You have entered an invalid community path"
export const INVALID_DATE_FORMAT: string = "Invalid date format"
export const DUPLICATE_ACCESS_POINT_ERROR: string = "An access point with this name exists. Provide a unique name"
export const DUPLICATE_HOUSE_NUMBER_ERROR = "Duplicate buildig/house number"
export const DUPLICATE_RECORD_ERROR = "Duplicate record found"

// Push notification strings
export const REQUEST_APPROVED: string = "Request Approved!"
export const REQUEST_DENIED: string = "Request Denied!"

export const REQUEST_DENIED_BODY: string = "Whoops! You are now a member of "
export const REQUEST_APPROVED_BODY: string = "Congratulations! You are now a member of "
export const REQUEST_INVITE_ERROR: string = "There was an error creating member invite"
export const COMMUNITY_MEMBER_AUTHORIZED_USER_DUPLICATE: string = "This member request is either being reviewed or exists in this community"
export const REQUEST_INVITE_DUPLICATE: string = "This member already exists or has a pending join requests. Kindly check and try again"