
export const DUPLICATE_ACCOUNT_ERROR: string = "An account with this email exists. Login or choose another email address"
export const DUPLICATE_BANK_ERROR: string = "A bank account with this credetials exists"
export const INVALID_LOGIN_ERROR: string = "You have entered an invalid username or password"
export const DUPLICATE_ADD_ON_REQUEST_ERROR: string = "A pending request was found. Kindly wait or contact customer service"
export const INVALID_OTP: string = "You have entered an invalid (O)ne (T)ime (P)assword"
export const INVALID_ACCESS_TIME: string = "You must set time within 24 hours"
export const PAST_ACCESS_TIME: string = "You can not set time in the past"
export const DUPLICATE_COMMUNITY_JOIN_REQUEST: string = "You have a pending request. Kindly wait until its approved or contact the community admin"
export const DUPLICATE_COMMUNITY_MEMBER_REQUEST: string = "You are already a member of this residential/social community"
export const INVALID_INVITE_VALIDITY: string = "You must enter a time in the future"
